function About() {
  return (
    <div className="about">
      <h1>About</h1>
      <p>This is a fullstack application built with:</p>
      <ul>
        <li><strong>Backend:</strong> Spring Boot 3.2 with Java 21</li>
        <li><strong>Frontend:</strong> React 18 with TypeScript</li>
        <li><strong>Build Tool:</strong> Vite</li>
        <li><strong>Data Fetching:</strong> TanStack Query</li>
      </ul>
      <p>Generated by mITyFactory</p>
      <style>{`
        .about {
          max-width: 600px;
          margin: 0 auto;
        }
        h1 {
          color: #e94560;
          margin-bottom: 1rem;
        }
        ul {
          list-style: none;
          padding: 0;
          margin: 1rem 0;
        }
        li {
          padding: 0.5rem 0;
          border-bottom: 1px solid #2a2a4a;
        }
      `}</style>
    </div>
  )
}

export default About
