import { Component } from '@angular/core';

@Component({
  selector: 'app-about',
  standalone: true,
  template: `
    <div class="about">
      <h1>About</h1>
      <p>This application was generated by mITyFactory.</p>
      <p>Built with Angular 17+, TypeScript, and standalone components.</p>
    </div>
  `,
  styles: [`
    .about {
      text-align: center;
    }
    h1 {
      color: #dd0031;
      margin-bottom: 1rem;
    }
    p {
      color: #666;
      margin: 0.5rem 0;
    }
  `]
})
export class AboutComponent {}
