<script setup lang="ts">
</script>

<template>
  <div class="about">
    <h1>About</h1>
    <p>This application was generated by mITyFactory.</p>
    <p>Built with Vue 3, TypeScript, Vite, and Pinia.</p>
  </div>
</template>

<style scoped>
.about {
  text-align: center;
}

h1 {
  color: #42b883;
}

p {
  color: #666;
  margin: 0.5rem 0;
}
</style>
